[data]
# User information
email = "drew@axol.io"
name = "Hydepwns"

# Oh My Zsh configuration
oh_my_zsh_theme = "robbyrussell"
oh_my_zsh_plugins = "git"
starship = true

# Personal flag for SSH templates
personal = true

# Tool configurations
rbenv = false
ohmyzsh = true
nvm = false
nodejs = true
asdf = true
elixir = true
erlang = true
lua = true
direnv = true
devenv = false
nix = true
llvm = false
postgres = false
psql = false
foundry = false
huff = false
solana = false
orbstack = false
tailscale = true
onepassword = true
aws = true
infisical = true
work = false

# Platform-specific
brewPrefix = "/opt/homebrew"
